GameStation/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GameStation.Models;
using GameStation.ViewModel;
using AutoMapper;
using GameStation.Mapper;
using GameStation.Filter;
using GameStation.Repository;

namespace GameStation.Controllers
{
    public class ReviewsController : Controller
    {
        private ReviewRepository ReviewRepository;
        private GameRepository GameRepository;

        public ReviewsController(ReviewRepository reviewRepository, GameRepository gameRepository)
        {
            ReviewRepository = reviewRepository;
            GameRepository = gameRepository;
        }

        // GET: Reviews
        public ActionResult Index()
        {
            return View(ReviewRepository.GetAllReviewsByGame());
        }

        #region Upvotes

        [AuthentificationFilter]
        public ActionResult Upvote(int? GameId, int? UserId, bool? isUpvote)
        {
            if (GameId == null || UserId == null || isUpvote == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = ReviewRepository.GetReviewByGame_User((int) GameId, (int) UserId);
            if (review == null)
            {
                return HttpNotFound();
            }
            if (isUpvote == true)
                review.Vote++;
            else
                review.Vote--;
            ReviewRepository.UpdateReview(review);
            return RedirectToAction("Details", "Games", new { id = review.GameId });
        }

        #endregion

        #region Detail

        // GET: Reviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = ReviewRepository.GetReviewById((int) id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        #endregion

        #region Create
        // GET: Reviews/Create
        [AuthentificationFilter]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = GameRepository.GetGameById((int) id);
            int UserId = (int)this.Session["UserID"];
            if (ReviewRepository.GetReviewByGame_User(game.ID, UserId) != null)
            {
                TempData["error"] = "You have already reviewed this game";
                return RedirectToAction("Details", "Games", new { id = game.ID });
            }
            if (game == null)
            {
                return HttpNotFound();
            }
            this.Session["GameId"] = id; //we need this to transfert the GameId to the method below
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Vote,isRecommanded,Description,GameId,UserId")] Review review)
        {
           review.GameId = (int)this.Session["GameId"];
           this.Session["GameId"] = null; //we don't need the id anymore
            review.UserId = (int)this.Session["UserID"];
            if (ModelState.IsValid)
            {
                ReviewRepository.AddReview(review);
                return RedirectToAction("Details", "Games", new { id = review.GameId});
            }
            ReviewViewModel reviewViewModel = AutoMapperConfig.ReviewMapper().Map<Review, ReviewViewModel>(review);

            return View(reviewViewModel);
        }

        #endregion

        #region Edit

        // GET: Reviews/Edit/5
        [AuthentificationFilter]
        public ActionResult Edit(int? GameId, int? UserId)
        {
            if (GameId == null || UserId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = ReviewRepository.GetReviewByGame_User((int) GameId, (int) UserId);
            if (review == null || UserId != review.UserId)
            {
                return HttpNotFound();
            }
            ReviewViewModel reviewViewModel = AutoMapperConfig.ReviewMapper().Map<Review, ReviewViewModel>(review);
            return View(reviewViewModel);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Vote,isRecommanded,Description,GameId,UserId")] Review review)
        {
            if (ModelState.IsValid)
            {
                ReviewRepository.UpdateReview(review);
                return RedirectToAction("Details", "Games", new { id = review.GameId });
            }
            ReviewViewModel reviewViewModel = AutoMapperConfig.ReviewMapper().Map<Review, ReviewViewModel>(review);
            return View(reviewViewModel);
        }

        #endregion

        #region Delete

        // GET: Reviews/Delete/5
        [AuthentificationFilter]
        public ActionResult Delete(int? GameId, int? UserId)
        {
            if (GameId == null || UserId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = ReviewRepository.GetReviewByGame_User((int)GameId, (int)UserId);
            if (review == null || UserId != review.UserId)
            {
                return HttpNotFound();
            }
            ReviewViewModel reviewViewModel = AutoMapperConfig.ReviewMapper().Map<Review, ReviewViewModel>(review);
            return View(reviewViewModel);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int GameId, int UserId)
        {
            Review review = ReviewRepository.GetReviewByGame_User((int)GameId, (int)UserId);
            ReviewRepository.DeleteReview(review);
            return RedirectToAction("Details", "Games", new { id= GameId});
        }

#endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                ReviewRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GameStation/Views/Reviews/Create.cshtml
@model GameStation.ViewModel.ReviewViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create a Review</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.isRecommanded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isRecommanded)
                    @Html.ValidationMessageFor(model => model.isRecommanded, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameStation/Views/Reviews/Delete.cshtml
@model GameStation.ViewModel.ReviewViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Review</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Vote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vote)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isRecommanded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isRecommanded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GameName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GameName)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Details", "Games", new { id = Model.GameId}, null)
        </div>
    }
</div>

GameStation/Views/Reviews/Details.cshtml
@model GameStation.ViewModel.ReviewViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Review</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Vote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vote)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isRecommanded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isRecommanded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Game.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Game.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Username)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GameStation/Views/Reviews/Edit.cshtml
@model GameStation.ViewModel.ReviewViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.isRecommanded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isRecommanded)
                    @Html.ValidationMessageFor(model => model.isRecommanded, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.GameId)

        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.Vote)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Game", "Details", "Games", new { id= Model.GameId }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameStation/Views/Reviews/Index.cshtml
@model IEnumerable<GameStation.Models.Review>

@foreach (var item in Model)
{
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(modelItem => item.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User.Username)
        </dt>
        <dd>
            @Html.DisplayFor(modelItem => item.User.Username)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vote)
        </dt>
        <dd>
            @Html.DisplayFor(modelItem => item.Vote)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.isRecommanded)
        </dt>
        <dd>
            @if (item.isRecommanded)
            {
                <div>Recommanded </div>
            }
            else
            {
                <div>NotRecommanded </div>
            }
        </dd>
    </dl>
    <div>
        <strong> review was usefull?</strong>
        <button type="button" class="btn btn-success">
            @Html.ActionLink("Yes", "Upvote", "Reviews", new { GameId = item.GameId, UserId = item.UserId, isUpvote = true }, new { style = "color:white" })
        </button>
        <button type="button" class="btn btn-danger">
            @Html.ActionLink("No", "Upvote", "Reviews", new { GameId = item.GameId, UserId = item.UserId, isUpvote = false }, new { style = "color:white" })
        </button>

        @if (this.Session["UserID"] != null && item.UserId == (int)this.Session["UserID"])
        {
            @Html.ActionLink("Delete", "Delete", "Reviews", new { GameId = item.GameId, UserId = item.UserId }, null)

            @Html.ActionLink("Edit", "Edit", "Reviews", new { GameId = item.GameId, UserId = item.UserId }, null)
        }
    </div>
    <hr />
}