GameStation/Models/Question.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GameId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}

GameStation/Controllers/AnswersController.cs
using GameStation.Filter;
using GameStation.Mapper;
using GameStation.Models;
using GameStation.Repository;
using GameStation.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GameStation.Controllers
{
    public class AnswersController : Controller
    {
        private AnswerRepository AnswerRepository;
        private QuestionRepository QuestionRepository;

        public AnswersController(AnswerRepository answerRepository, QuestionRepository questionRepository)
        {
            AnswerRepository = answerRepository;
            QuestionRepository = questionRepository;
        }

        // GET: Answers
        public ActionResult Index()
        {
            return View(AnswerRepository.GetAllAnswersByQuestion());
        }

        #region Votes

        [AuthentificationFilter]
        public ActionResult Upvote(int? AnswerId, int? UserId, bool? isUpvote)
        {
            if (AnswerId == null || UserId == null || isUpvote == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = AnswerRepository.GetAnswerByUser((int)AnswerId, (int)UserId);
            if (answer == null)
            {
                return HttpNotFound();
            }
            if (isUpvote == true)
                answer.Vote++;
            else
                answer.Vote--;
            AnswerRepository.UpdateAnswer(answer);
            return RedirectToAction("Details", "Questions", new { id = answer.QuestionId });
        }

        #endregion

        #region Detail

        // GET: Answers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = AnswerRepository.GetAnswerById((int)id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            AnswerViewModel answerViewModel = AutoMapperConfig.AnswerMapper().Map<Answer, AnswerViewModel>(answer);
            answerViewModel.QuestionTitle = answer.Question.Title;
            return View(answerViewModel);
        }

        #endregion

        #region Create
        // GET: Answers/Create
        [AuthentificationFilter]
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = QuestionRepository.GetQuestionById((int)id);
            int UserId = (int)this.Session["UserID"];
            if (question == null)
            {
                return HttpNotFound();
            }
            this.Session["QuestionId"] = id; //we need this, because the QuestionId won't transfe to the method below. TODO Find a solution..
            return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "QuestionId,Vote,Description,UserId")] Answer answer)
        {
            answer.QuestionId = (int)this.Session["QuestionId"];
            this.Session["QuestionId"] = null; //we don't need the id anymore
            answer.UserId = (int)this.Session["UserID"];

            if (ModelState.IsValid)
            {
                AnswerRepository.AddAnswer(answer);
                return RedirectToAction("Details", "Questions", new { id = answer.QuestionId });
            }
            AnswerViewModel answerViewModel = AutoMapperConfig.AnswerMapper().Map<Answer, AnswerViewModel>(answer);
            answerViewModel.QuestionTitle = answer.Question.Title;
            return View(answerViewModel);
        }

        #endregion

        #region Edit

        // GET: Answers/Edit/5
        [AuthentificationFilter]
        public ActionResult Edit(int? AnswerId, int? UserId)
        {
            if (AnswerId == null || UserId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = AnswerRepository.GetAnswerByUser((int)AnswerId, (int)UserId);
            if (answer == null || UserId != answer.UserId)
            {
                return HttpNotFound();
            }

            AnswerViewModel answerViewModel = AutoMapperConfig.AnswerMapper().Map<Answer, AnswerViewModel>(answer);
            answerViewModel.QuestionTitle = answer.Question.Title;
            return View(answerViewModel);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,QuestionId,Vote,Description,UserId")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                AnswerRepository.UpdateAnswer(answer);
                return RedirectToAction("Details", "Questions", new { id = answer.QuestionId });
            }
            AnswerViewModel answerViewModel = AutoMapperConfig.AnswerMapper().Map<Answer, AnswerViewModel>(answer);
            answerViewModel.QuestionTitle = answer.Question.Title;
            return View(answerViewModel);
        }

        #endregion

        #region Delete

        // GET: Answers/Delete/5
        [AuthentificationFilter]
        public ActionResult Delete(int? AnswerId, int? UserId)
        {
            if (AnswerId == null || UserId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = AnswerRepository.GetAnswerByUser((int)AnswerId, (int)UserId);
            if (answer == null || UserId != answer.UserId)
            {
                return HttpNotFound();
            }
            AnswerViewModel answerViewModel = AutoMapperConfig.AnswerMapper().Map<Answer, AnswerViewModel>(answer);
            answerViewModel.QuestionTitle = answer.Question.Title;
            return View(answerViewModel);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int AnswerId, int UserId)
        {
            Answer answer = AnswerRepository.GetAnswerByUser((int)AnswerId, (int)UserId);
            int questionId = answer.QuestionId;
            AnswerRepository.DeleteAnswer(answer);
            return RedirectToAction("Details", "Questions", new { id = questionId });
        }

        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                AnswerRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GameStation/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GameStation.Models;
using GameStation.Filter;
using GameStation.Repository;
using GameStation.ViewModel;
using GameStation.Mapper;

namespace GameStation.Controllers
{
    public class QuestionsController : Controller
    {
        private QuestionRepository QuestionRepository;
        private GameRepository GameRepository;
        //private UserRepository UserRepository;

        public QuestionsController(QuestionRepository questionRepository, GameRepository gameRepository)
        {
            QuestionRepository = questionRepository;
            GameRepository = gameRepository;
        }

        // GET: Questions
        public ActionResult Index()
        {
            var questions = QuestionRepository.GetAllQuestions();
            List<QuestionViewModel> questionsViewModel = new List<QuestionViewModel>();
            foreach(var q in questions)
            {
                QuestionViewModel questionViewModel = AutoMapperConfig.QuestionMapper().Map<Question, QuestionViewModel>(q);
                questionsViewModel.Add(questionViewModel);
            }

            return View(questionsViewModel);
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = QuestionRepository.GetQuestionById((int)id);
            if (question == null)
            {
                return HttpNotFound();
            }
            QuestionViewModel questionViewModel = AutoMapperConfig.QuestionMapper().Map<Question, QuestionViewModel>(question);
            questionViewModel.QuestionCreator = question.User.Username;
            return View(questionViewModel);
        }

        // GET: Questions/Create
        [AuthentificationFilter]
        public ActionResult Create()
        {
            ViewBag.GameId = new SelectList(GameRepository.GetAllGames(), "ID", "Name");
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Description,UserId,GameId")] Question question)
        {
            question.UserId = (int)this.Session["UserID"];

            if (ModelState.IsValid)
            {
                QuestionRepository.AddQuestionDB(question);
                return RedirectToAction("Index");
            }

            ViewBag.GameId = new SelectList(GameRepository.GetAllGames(), "ID", "Name", question.GameId);
            QuestionViewModel questionViewModel = AutoMapperConfig.QuestionMapper().Map<Question, QuestionViewModel>(question);
            return View(questionViewModel);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = QuestionRepository.GetQuestionById((int)id);
            if (question == null)
            {
                return HttpNotFound();
            }
            QuestionViewModel questionViewModel = AutoMapperConfig.QuestionMapper().Map<Question, QuestionViewModel>(question);
            ViewBag.GameId = new SelectList(GameRepository.GetAllGames(), "ID", "Name", question.GameId);
            return View(questionViewModel);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Description,UserId,GameId")] Question question)
        {
            if (ModelState.IsValid)
            {
                QuestionRepository.UpdateQuestionDB(question);
                return RedirectToAction("Index");
            }
            QuestionViewModel questionViewModel = AutoMapperConfig.QuestionMapper().Map<Question, QuestionViewModel>(question);
            ViewBag.GameId = new SelectList(GameRepository.GetAllGames(), "ID", "Name", question.GameId);
            return View(questionViewModel);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = QuestionRepository.GetQuestionById((int)id);
            if (question == null)
            {
                return HttpNotFound();
            }
            if (question.User.ID != (int)this.Session["UserID"])
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            QuestionViewModel questionViewModel = AutoMapperConfig.QuestionMapper().Map<Question, QuestionViewModel>(question);
            questionViewModel.QuestionCreator = question.User.Username;
            return View(questionViewModel);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QuestionRepository.DeleteQuestion(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                QuestionRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GameStation/Views/Questions/Create.cshtml
@model GameStation.ViewModel.QuestionViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GameId, "GameId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GameId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GameId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameStation/Views/Questions/Delete.cshtml
@model GameStation.ViewModel.QuestionViewModel
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Game.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Game.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Username)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GameStation/Views/Questions/Details.cshtml
@model GameStation.ViewModel.QuestionViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Game.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Game.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Username)
        </dd>

    </dl>
</div>

<h3>Answers</h3>

<hr />
<br />

@{Html.RenderPartial("~/Views/Answers/Index.cshtml", Model.Answers);}

<hr />

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Add Answer", "Create", "Answers", new { id = Model.ID }, null) |

    @Html.ActionLink("Back to List", "Index")
</p>

GameStation/Views/Questions/Edit.cshtml
@model GameStation.ViewModel.QuestionViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GameId, "GameId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GameId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GameId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameStation/Views/Questions/Index.cshtml
@model IEnumerable<GameStation.ViewModel.QuestionViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Game.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Username)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Game.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Username)
        </td>
        <td>

            @if (this.Session["UserID"] != null && item.UserId == (int)this.Session["UserID"])
            {
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) 
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            }
            @Html.ActionLink("Details", "Details", new { id = item.ID })
        </td>
    </tr>
}

</table>